version: "3.9"
services: 
  chanchito:
    build: .
    ports: 
      - "3000:3000" 
    links: 
      - monguito
  monguito:
    image: mongo
    ports: 
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=nico
      - MONGO-INITDB_ROOT_PASSWORS=password
